
import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;

public class OpcionesDistritos extends HttpServlet {

    public void doGet(HttpServletRequest peticion, HttpServletResponse respuesta) throws ServletException, IOException {

        //1 proceso
        //recogemos las variables que nos llegan por URL
        String id_distrito = peticion.getParameter("id_distrito");
        String nombre_distrito = peticion.getParameter("nombre");

        HttpSession sesion = peticion.getSession(true);
        sesion.setAttribute("id_distrito", id_distrito);
        sesion.setAttribute("nombre_distrito", nombre_distrito);

        //2 salida
        respuesta.setContentType("text/html");

        //creamos canal de salida
        PrintWriter pw = respuesta.getWriter();
        pw.println("<HTML>");
        pw.println("<HEAD>");
        pw.println(" <style>\n"
                + "\n"
                + "        .cabecera{\n"
                + "            width: 100%;\n"
                + "            height: 70px;\n"
                + "            background: rgb(9, 9, 74);\n"
                + "        }\n"
                + "        \n"
                + "        h1{\n"
                + "            color: white;\n"
                + "            font-size: 50px;\n"
                + "        }\n"
                + "        h2{\n"
                + "            color: black;\n"
                + "            font-size: 50px;\n"
                + "        }\n"
                + "\n"
                + "    </style>");
        
        pw.println("</HEAD>");
        pw.println("<BODY>");
        pw.println("<DIV style=\" position:absolute;top:70px;left:1200px\">");
        pw.println("<h2>" + id_distrito + " | " + nombre_distrito + "</h2>");
        pw.println("</DIV>");
       
        pw.println("<CENTER>");

        pw.println("<div class=\"cabecera\"><h1>Sistema de quejas</h1></div>");
        pw.print("<!-- Image Map Generated by http://www.image-map.net/ -->\n"
                + "<img src=\"/sistema_quejas/img/consultasymarcar.jpg\" usemap=\"#image-map\">\n"
                + "\n"
                + "<map name=\"image-map\">\n"
                + "    <area target=\"\" alt=\"Marcar\" title=\"Marcar\" href=\"http://localhost:8080/examples/servlets/servlet/MarcarQueja\" coords=\"281,26,222,25,165,34,141,39,109,50,79,62,56,74,48,87,35,97,30,107,23,121,18,139,18,160,25,177,36,189,47,204,67,214,85,223,100,230,116,238,134,243,152,247,181,252,195,256,208,257,204,237,203,214,207,193,214,167,222,152,229,143,237,132,251,119,260,105,270,84,281,61,281,42\" shape=\"poly\">\n"
                + "    <area target=\"\" alt=\"Consultar\" title=\"Consultar\" href=\"http://localhost:8080/examples/servlets/servlet/ConsultarQuejas\" coords=\"283,25,310,27,328,31,351,35,368,40,386,46,404,54,416,58,431,68,445,80,459,91,473,110,479,124,480,140,478,162,468,178,459,192,446,203,424,216,402,226,381,240,347,246,324,251,291,255,269,255,243,258,220,258,210,255,206,223,211,180,216,157,232,137,247,123,260,106,272,85,278,71,286,55\" shape=\"poly\">\n"
                + "</map>");

        pw.print("<div class=\"footer\"><h2 class=\"foot_span\">Seleccione una opción</h2></div>");
        pw.println("<hr>\n"
                + "<font color=\"gray\">\n"
                + "    <small>&copy;Todos los derechos reservados. Losquejicas.com 2022</small>");
        pw.println("</CENTER>");
        pw.println("</BODY>");
        pw.println("</HTML>");
    }
}
